### ISSUE TITLE
Custom 'BuildTimestampProvider' stopped working using tycho version 4.0.10

### ISSUE THREAD

**Issue by ChetanKaila** [eclipse-tycho/tycho#5738]
I have implemented a custom BuildTimestampProvider in my OSGi-based application to update the .qualifier with the current timestamp only for bundles that have actually changed, instead of updating all bundles.

The custom timestamp provider is implemented as follows:

```
@Component(role = BuildTimestampProvider.class, hint = "file")
public class FileBuildTimstampProvider implementes BuildTimestampProvider {

//I have overrided the method to customize the behaviour
public Date getTimestamp(MavenSession session, MavenProject project, MojoExecution execution){

}

}
```

It is used in the pom.xml as shown below:

```
<plugin>
 <groupId>org.eclipse.tycho</groupId>
 <artifactId>tycho-packaging-plugin</artifactId>
 <version>2.7.5</version>
 <depedencies>
  <dependecy>
   <groupId>com.team.osapp</groupId>
   <artifactId>buildtimstamp</artifactId>
  <version>0.0.1</version>
 </dependency>
 <configuration>
   <deployableFeature>true</deployableFeatuer>
   <timestampProvider>file</timestampProvider>
   <file.timestamps>/home/timestamps.properties</file.timestamps>
 </configuration>
<depedencies>
</plugin>
```

This setup works with Tycho version 2.7.5 but stopped working after upgrading the application to Tycho version 4.0.10. What changes are required to make it work with the newer version of Tycho?

**Comment by laeubi** [comment]
> This setup works with Tycho version 2.7.5 but stopped working after upgrading the application to Tycho version 4.0.10. What changes are required to make it work with the newer version of Tycho?

Have you recompiled your custom provider using Tycho 4.x API? By the way 4.x is EOL now and 5.x is the current latest release so you maybe want to upgrade to 5.x anyways.

**Comment by ChetanKaila** [comment]
Yes, I tried compiling a custom `FileBuildTimstampProvider` class with tycho version 4.0.10 and got the error shown below:

```
[ERROR] FileBuildTimestampProvider.java:[27,38] cannot find symbol
[ERROR]   symbol:   class BuildTimestampProvider
[ERROR]   location: package org.eclipse.tycho.buildversion
```

There are errors for other packages too, but the primary issue is that `org.eclipse.tycho.buildversion.BuildTimestampProvider` no longer exist in the new version. 

A sample pom for tycho version 4.0.10 looks like this: 

```

<properties>
	<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
</properties>
    <dependencies>
	    <dependency>
	      <groupId>org.eclipse.tycho</groupId>
	      <artifactId>tycho-packaging-plugin</artifactId>
	      <version>4.0.10</version>
	      <type>maven-plugin</type>
	    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.codehaus.plexus</groupId>
        <artifactId>plexus-component-metadata</artifactId>
    <version>2.0.0</version>
    <executions>
        <execution>
            <id>process-classes</id>
            <goals>
                <goal>generate-metadata</goal>
            </goals>
        </execution>
    </executions>
      </plugin>
    </plugins>
  </build>
```

It works when we change `<version>4.0.10</version>` to `2.7.5`

**Comment by nitind** [comment]
@ChetanKaila Looks to me like the interface was moved into a different package when it added a new required method. Does it work if you update and recompile your provider?

**Comment by laeubi** [comment]
The interface is now in the `tycho-spi` module: https://github.com/eclipse-tycho/tycho/blob/main/tycho-spi/src/main/java/org/eclipse/tycho/build/BuildTimestampProvider.java#L22
